# Generated by Django 4.1.7 on 2023-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
                ('profile_picture', models.CharField(default='', max_length=256)),
                ('cover_photo', models.CharField(default='', max_length=256)),
                ('date_of_joining', models.DateTimeField(auto_now=True)),
                ('requests_sent_to_groups', models.CharField(default='', max_length=128, null=True)),
                ('pending_requests_to_groups', models.CharField(default='', max_length=128, null=True)),
                ('approved_requests', models.CharField(default='', max_length=128, null=True)),
                ('user_type', models.CharField(choices=[('simple_user', 'Simple User'), ('group_member', 'Group Member'), ('registered', 'Registered'), ('admin', 'Admin')], default='simple_user', max_length=20)),
            ],
        ),
    ]
