# Generated by Django 4.1.7 on 2023-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_user_cover_photo_remove_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default=' ', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default=' ', max_length=256),
        ),
    ]
