# Generated by Django 4.1.7 on 2023-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_cover_photo_user_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('post_text', models.CharField(max_length=256)),
                ('post_image', models.CharField(max_length=256)),
                ('num_of_likes', models.IntegerField()),
                ('num_of_dislikes', models.IntegerField()),
                ('liked_by', models.CharField(max_length=1000)),
                ('disliked_by', models.CharField(max_length=1000)),
            ],
        ),
    ]
