# Generated by Django 4.1.7 on 2023-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_post_date_added_alter_post_disliked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_img',
            field=models.CharField(default=True, max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(default=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(default=True, max_length=1056),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
