# Generated by Django 4.1.5 on 2023-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_post_user_img_post_user_name_alter_post_post_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prob_img', models.CharField(default=True, max_length=256)),
                ('Prob_name', models.CharField(default=True, max_length=256)),
                ('solvedby', models.IntegerField(default=0)),
                ('Prob_description', models.TextField(default='')),
                ('Prob_isactive', models.CharField(default='True', max_length=256)),
                ('output', models.CharField(default='', max_length=512)),
                ('solution', models.TextField(default='')),
                ('Prob_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
